name: CI

on: push

jobs:
  build:
    env:
      REPO: nim-eternity
      NIM_VERSION: 1.2.0

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run Tests
      run: docker run -v `pwd`:/usr/src/app -w /usr/src/app nimlang/nim:$NIM_VERSION nimble test -y

